_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
                - 62
            "4": 3.10.13
            "5": 0.19.8
            "6": 4.53.3
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
alpha:
    value: 0.5
audio_path:
    value: /workspace/datasets/CREMA-D/AudioWAV
batch_size:
    value: 64
ckpt_path:
    value: /workspace/emotion_KD250628/MKD/CREMA_D_MKD/MKD/ckpt
dataset:
    value: CREMAD
epochs:
    value: 200
fps:
    value: 1
fusion_method:
    value: sum
gpu_ids:
    value: 0, 1
learning_rate:
    value: 0.001
lr_decay_ratio:
    value: 0.1
lr_decay_step:
    value: 70
modulation:
    value: Normal
modulation_ends:
    value: 50
modulation_starts:
    value: 0
optimizer:
    value: sgd
random_seed:
    value: 444
small_dataset:
    value: true
train:
    value: true
unimodal:
    value: true
unimodal_modality:
    value: audio
use_video_frames:
    value: 3
visual_path:
    value: /workspace/datasets/CREMA-D/
